### ISSUE TITLE
Nginx Welcome screen

### ISSUE THREAD

**Issue by jimmyt2003** [vesselinv/vagrant-lemp#3]
I want files just from the directory where my vagrant box is

config.vm.synced_folder '.', '/home/vagrant/code'

I edited to the line above but just see the nginx welcome screen

**Comment by vesselinv** [comment]
Your Vagrantfile `synced_folder` config looks alright. To change the nginx home directory, you need to update the root directive inside `/etc/nginx/sites-available/default` to `/home/vagrant/code`.

**Comment by jimmyt2003** [comment]
Thanks!
