### ISSUE TITLE
Cant mount NFS Share

### ISSUE THREAD

**Issue by sshrestha-navarts** [vesselinv/vagrant-lemp#4]
Hi, I gave your project a spin, getting the following error message on OSX (10.10): 

    ==> default: Mounting NFS shared folders...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    mount -o 'vers=3,udp' 10.4.4.1:'/Users/sshrestha' /home/vagrant/code

    Stdout from the command:

    Stderr from the command:

    mount.nfs: access denied by server while mounting 10.4.4.1:/Users/sshrestha

    ➜  vagrant-lemp git:(master)

**Comment by vesselinv** [comment]
Thanks for reporting this!
